### PR TITLE
make attributes protected

### PR DESCRIPTION
**Pull request by AndreySlashman**
I think it will be useful for extending

### CODE REVIEW

**Comment by duncan3dc** [comment]
Thanks @AndreySlashman, do you have a use case for extending?

**Comment by AndreySlashman** [comment]
@duncan3dc Yes, I needed to get the number of running forks

**Comment by duncan3dc** [comment]
Cool, would adding a `getPIDs()` method give you what you need? Something like:

``` php
public function getPIDs()
{
    return array_values($this->threads);
}
```

**Comment by AndreySlashman** [comment]
Yes, it would

But making the properties protected would help someone to achieve something more

But for me it is ok

I can make a new commit and revert the previous one if you want

-- 
С уважением, Жилин Андрей

Включено 14 апреля 2016 г. в 15:33:20, Craig Duncan (notifications@github.com) написал:

Cool, would adding a getPIDs() method give you what you need? Something like:

public function getPIDs()
{
    return array_values($this->threads);
}

**Comment by duncan3dc** [comment]
Yeh If you'd like to contribute a `getPIDs()` method that would be great. I'd prefer to keep the properties/methods private so that I can make breaking changes freely without worrying about downstream

**Comment by AndreySlashman** [comment]
@duncan3dc Implemented, seems to be ok now

**Comment by duncan3dc** [comment]
Great stuff, thanks :+1:

**Pull request merged**
